#= require foundation-sites/dist/js/foundation
# Disabled, since they use ES6, which is currently not copatible with uglifier
# require foundation-sites/js/foundation.core
# require foundation-sites/js/foundation.util.mediaQuery
#
# require foundation-sites/js/foundation.abide
# require foundation-sites/js/foundation.accordion
# require foundation-sites/js/foundation.accordionMenu
# require foundation-sites/js/foundation.drilldown
# require foundation-sites/js/foundation.dropdown
# require foundation-sites/js/foundation.dropdownMenu
# require foundation-sites/js/foundation.equalizer
# require foundation-sites/js/foundation.interchange
# require foundation-sites/js/foundation.magellan
# require foundation-sites/js/foundation.offcanvas
# require foundation-sites/js/foundation.orbit
# require foundation-sites/js/foundation.responsiveMenu
# require foundation-sites/js/foundation.responsiveToggle
# require foundation-sites/js/foundation.reveal
# require foundation-sites/js/foundation.slider
# require foundation-sites/js/foundation.sticky
# require foundation-sites/js/foundation.tabs
# require foundation-sites/js/foundation.toggler
# require foundation-sites/js/foundation.tooltip
# require foundation-sites/js/foundation.util.box
# require foundation-sites/js/foundation.util.keyboard
# require foundation-sites/js/foundation.util.motion
# require foundation-sites/js/foundation.util.nest
# require foundation-sites/js/foundation.util.timerAndImageLoader
# require foundation-sites/js/foundation.util.touch
# require foundation-sites/js/foundation.util.triggers
# require foundation-sites/js/foundation.zf.responsiveAccordionTabs
