inherit_gem:
  ThunderKey-rubocop: rubocop.yml

# Disable for now
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ContextWording:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/InstanceVariable:
  Enabled: false
RSpec/SubjectStub:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
RSpec/ExpectInHook:
  Enabled: false
RSpec/ImplicitSubject:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/DescribeClass:
  Enabled: false
RSpec/AnyInstance:
  Enabled: false
