# See:
# * https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml
# * https://github.com/rubocop-hq/rubocop/blob/master/config/enabled.yml
# * https://github.com/rubocop-hq/rubocop/blob/master/config/disabled.yml

Metrics/MethodLength:
  Max: 15

Metrics/LineLength:
  Max: 100
  IgnoredPatterns:
    # allow string representations of objects (in tests)
    - !ruby/regexp '/#<[A-Za-z0-9:]+ [a-z0-9]+: .*>/'

Style/PercentLiteralDelimiters:
  # Specify the default preferred delimiter for all types with the 'default' key
  # Override individual delimiters (even with default specified) by specifying
  # an individual key
  PreferredDelimiters:
    default: ()
    '%i': '()'
    '%I': '()'
    '%r': '{}'
    '%w': '()'
    '%W': '()'
    '%q': '{}'
    '%Q': '{}'
Style/BarePercentLiterals:
  EnforcedStyle: percent_q

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/BlockLength:
  ExcludedMethods:
    # ignore rspec methods
    - context
    - describe
    - it
    - define
    - shared_examples

# Trailing Commas

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

# Alignments

Layout/DefEndAlignment:
  EnforcedStyleAlignWith: def
Layout/BlockAlignment:
  EnforcedStyleAlignWith: start_of_line
Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line
Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/CaseIndentation:
  EnforcedStyle: end

# Disabled

Style/MethodDefParentheses:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/SpaceInsideBlockBraces:
  Enabled: false
Layout/ElseAlignment:
  Enabled: false
Naming/UncommunicativeMethodParamName:
  Enabled: false
Layout/ClosingHeredocIndentation:
  Enabled: false
Lint/AssignmentInCondition:
  Enabled: false
Layout/IndentHeredoc:
  Enabled: false
