language: ruby
rvm:
  - ruby-2.4.0
dist: trusty
#sudo: required
#addons:
#  apt:
#    packages:
#    - mysql-server-5.6
#    - mysql-client-core-5.6
#    - mysql-client-5.6
#services:
#  - mysql
env:
  - "RAILS_ENV=test"
before_script:
  - 'echo "test:\n  secret_key_base: 2980cae3ee5f6d2b8f030f44a059305b2074ec767e8a67697012a741a808772942a6039025793e89cdf4a260d69684d5a9dff68659705d9bb08a3176e2c814c6" > config/secrets.yml'
  - bundle exec rake db:migrate
  - npm install -g bower
  - bower install
script:
  - bundle exec rspec
notifications:
  email:
    - nicolasganz37+travis@gmail.com
