language: ruby
rvm:
  - ruby-2.4.0
dist: trusty
#sudo: required
addons:
  code_climate:
    repo_token: 3f12d785dcf81dd2351e408e00f86af458b28a4c776edf55abe641df95a1f87f
#addons:
#  apt:
#    packages:
#    - mysql-server-5.6
#    - mysql-client-core-5.6
#    - mysql-client-5.6
services:
  - redis-server
#  - mysql
env:
  - "RAILS_ENV=test"
before_script:
  - cp config/secrets.yml.testing config/secrets.yml
  - bundle exec rake db:migrate
  - npm install -g bower
  - bower install
script:
  - bundle exec rspec
after_success:
  - bundle exec codeclimate-test-reporter
notifications:
  email:
    - nicolasganz37+travis@gmail.com
