language: ruby
rvm:
  - ruby-2.4.0
dist: trusty
#sudo: required
#addons:
#  apt:
#    packages:
#    - mysql-server-5.6
#    - mysql-client-core-5.6
#    - mysql-client-5.6
#services:
#  - mysql
env:
  - "RAILS_ENV=test"
before_script:
  - echo "test:\n  secret_key_base: b3e5376fa509458710aa3c48c3f484d1f86d9c79b56e76497546b4279bc69aeb0f92f294640852903f8585427bf29005ab2a84be47c6c047331cb7a091fb39c4" > config/secrets.yml
  - bundle exec rake db:migrate
  - npm install -g bower
  - bower install
script:
  - bundle exec rspec
notifications:
  email:
    - nicolasganz37+travis@gmail.com
