language: ruby
rvm:
  - ruby-2.4.0
dist: trusty
#sudo: required
#addons:
#  apt:
#    packages:
#    - mysql-server-5.6
#    - mysql-client-core-5.6
#    - mysql-client-5.6
#services:
#  - mysql
#before_install:
#  - mysql -e "CREATE DATABASE IF NOT EXISTS bands_test;" -uroot
#  - mysql -e "CREATE DATABASE IF NOT EXISTS musicbrainz_test;" -uroot
#  - mysql musicbrainz_test < ./db/musicbrainz_schema.sql -uroot
env:
  - "RAILS_ENV=test"
before_script:
  - bundle exec rake db:migrate
  - npm install -g bower
  - bower install
script:
  - bundle exec rspec
notifications:
  email:
    - nicolasganz37+travis@gmail.com
