language: ruby
rvm:
  - ruby-2.4.3
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
services:
  - redis-server
  - mysql
env:
  global:
    - "RAILS_ENV=test"
    - secure: "NXVOCmA1xZguffZrwOxa+jSzcPHDeWMvLH6xFsT3FqSMpt37KJRf66XAbd1oAvZ3XDDfg4+Y2QwZHzYJKyujDSMe57wMjEeITZLHqIgEEao+9MaBS/DnmHZKQTRyBWUEgG30HZC1V3B9r2otSaewBOSEJXaykQEPKyVNfdSBZ3C2b1B69m0etDBAuGf4hFDVCvUxtfUgxa51MFLV2vjMEa2bo9lSvYpDAVL5UMDJm5xiSx4Uc6Tr6tVQnHC9mukNiKennQlgm8NW3oVF2yprVPzzepxKZhWuAkAg/paiEHuovVWm3X3y89kEJsnuAuge3skthsFbRP5chqr+Hsc045ekRfGWqyWeB2DBgrDYoMeoyP38y1dkhCm841+8sCM0imDAxJXpbf8Lt9pdbhxBdtlbTy/s1TUr8AYmv0jCRcOtbkAhvReY1Sxp5GpV9e20p9x+UI6j1iD6PDPdBsu+qxc3Byy5FvCAF8NxD4DUl5MkQPRH3uMl3fPHW2WkOPsLnqJkzkrV7QWlDHnrgrgNSIbtBgmbiAc/PFJ6UANEKRkZLRR/4/eqr75GqDLQDxQWzL4XKe1nhlZf/JEc5928ZIedA6wtVqtUJN7kIbd0R3OAWd0YRUQcg+HlPtGBjQfC3etrj8XAlOgyQ+d645aWwp8IMIr8HkTO8YipM8mH6FM="
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS gaas_test'
before_script:
  - cp config/secrets.yml.travis config/secrets.yml
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:migrate
script:
  - bundle exec rspec
after_success:
  - bundle exec codeclimate-test-reporter
notifications:
  email:
    - nicolasganz37+travis@gmail.com
