language: ruby
rvm:
  - ruby-2.5.0
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
services:
  - redis-server
  - mysql
env:
  global:
    - "RAILS_ENV=test"
    - secure: "MxgEnWQ5NYao7beUnM/1l9ZBVSIE+AEP58Gf9csoHcCOpgiCUdmwCCcfh+rhB14wldYEs6iQlvfqARiDaoMOKieoI1CMiuPGA+aLqUaYkEHeHScq1LO+zLiM4G473oqo5QTv8bKpzerhDSC9DyRa/iF8WygUKZDkMtSLnsBuk9TjaAy3QYj3br47EhS0LXZs8JKktrzfx8RTHkRNIh4oheSamdXnA6nBr1DDBSx8HLJMFr8lCE3/UY0ej5pq4SaPVdrYCkOr9cXIya3cytXwd/nVn6LXHP9DVf1FMb2Ik8AhP2i0BHZzRNIDXGFmy+MhFN+Oc9GHRHfTEfZCAaKD5zTeweGH0j3WRVy0sFQezg3twel4J10z+ZdrW+4KfDXPDXWvrQD6N2iRBt9UIRiulFgmqYJfR9u+XqUO3fuHgkX/2Kv5rHGdvKL1KokTc1w6i2t85+EqCk/O3pdZCQY+iMkpgv57YM81qmvdmBln+/GCcCC2eTgvFVKTOGEybaUwHszYrxDN1/ng3gtga0Ci3oJzmduFMAX/0rFbqePvwnTkwzUjKI8ls2Cp4xLa9Hr4Vy7ZVRnwL0db7xosKOQQaYox8EP06mThFtfjvonhEYcuJ11wYxU58yXfsWSZRd1FF4DPGv7PAvGOu6RdufXTLKfCUXULb48ckCqa+MOdA4U="
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS gaas_test'
before_script:
  - cp config/secrets.yml.travis config/secrets.yml
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:migrate

  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
  - bundle exec rubocop
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  email:
    - nicolasganz37+travis@gmail.com
